$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: fasta reference file
    required:
      - fasta

  mutect2:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for mutect2
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to mutect2

  ensemble_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for ensemble_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      callers:
        type: array
        items:
            type: string
        description: list of callers that are included in the vcf ensemble
      support:
        type: integer
        description: how many callers must support variant to be included in ensembled vcf
      sort_order:
        type: string
        description: order which information about a variant should be kept ("vardict,mutect2")
      required:
        - sort_order
        - callers

  annotate:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for annotate
      container:
        type: string
        description: name or path to docker/singularity container
      vep_cache:
        type: string
        description: path to vep cache directory
      extra:
        type: string
        description: parameters that should be forwarded to vep annotate
      mode:
        type: string
        description: Used to make vep query online database, by setting mode to --database
      required:
        - extra
        - vep_cache


  tabix_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for tabix_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to tabix_vcf

  filter_vcf_on_format:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for filter_vcf_on_format
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: extra parameters that should be forwarded to filter_vcf_on_format
      filter:
        type: string
        description: filter parameters that should be forwarded to filter_vcf_on_format

  bgzip_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for bgzip
      container:
        type: string
        description: name or path to docker/singularity container

  merge_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for merge_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      skip_chrs:
        type: list
        description: list of chromosomes to skip
      extra:
        type: string
        description: parameters that should be forwarded to merge_vcf

  vardict:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for vardict
      container:
        type: string
        description: name or path to docker/singularity container
      extra:
        type: string
        description: parameters that should be forwarded to vardict
      bed_columns:
        type: string
        description: columns to use in bed file
      allele_frequency_threshold:
        type: string
        description: allele frequency threshold

  decompose:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for decompose
      container:
        type: string
        description: name or path to docker/singularity container

  normalize:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for normalize
      container:
        type: string
        description: name or path to docker/singularity container

  sort_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for sort_vcf
      container:
        type: string
        description: name or path to docker/singularity container

  required:
    - samples
    - units
    - reference
    - resources
    - default_container
