$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  resources:
    type: string
    description: Path to resources.yaml file
  default_container:
    type: string
    description: name or path to a default docker/singularity container
  reference:
    type: object
    properties:
      fasta:
        type: string
        description: fasta reference file
    required:
      - fasta

  mutect2:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for mutect2
      container:
        type: string
        description: name or path to docker/singularity container
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to mutect2

  merge_vcf:
    type: object
    properties:
      benchmark_repeats:
        type: integer
        description: set number of times benchmark should be repeated for merge_vcf
      container:
        type: string
        description: name or path to docker/singularity container
      input:
        type: list
        description: list of chromosomes to skip
      params:
        type: object
        properties:
          extra:
            type: string
            description: parameters that should be forwarded to merge_vcf

  required:
    - samples
    - units
    - reference
    - resources
    - default_container
