resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://marrip/common:1.1.0"

reference:
  fasta: "reference/WASH7P.fna"

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

filter_vcf_on_format:
  container: "docker://gmsuppsala/somatic:develop"

merge_vcf:
  container: "docker://gmsuppsala/somatic:develop"

bgzip_vcf:
  container: "docker://gmsuppsala/somatic:develop"

tabix_vcf:
  container: "docker://gmsuppsala/somatic:develop"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

sort_vcf:
  container: "docker://gmsuppsala/somatic:develop"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - mutect2
  sort_order: "vardict,mutect2"
