resources: "resources.yaml"
samples: "samples.tsv"
units: "units.tsv"

default_container: "docker://hydragenetics/common:0.0.1"

reference:
  fasta: "reference/HES45.fna"
  fai: "reference/HES45.fna.fai"
  design_bed: "reference/twist_DNA_solid.HES45.annotated.bed"

vardict:
  container: "docker://gmsuppsala/somatic:develop"
  bed_columns: "-c 1 -S 2 -E 3"

mutect2:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

mutect2_gvcf:
  container: "docker://hydragenetics/gatk4:4.1.9.0"

merge_vcf:
  container: "docker://hydragenetics/common:0.0.1"

merge_gvcf:
  container: "docker://hydragenetics/common:0.0.1"

bgzip_vcf:
  container: "docker://hydragenetics/common:0.0.1"

tabix_vcf:
  container: "docker://hydragenetics/common:0.0.1"

decompose:
  container: "docker://gmsuppsala/somatic:develop"

normalize:
  container: "docker://gmsuppsala/somatic:develop"

sort_vcf:
  container: "docker://hydragenetics/common:0.0.1"

ensemble_vcf:
  container: "docker://gmsuppsala/somatic:develop"
  callers:
    - vardict
    - mutect2
  sort_order: "vardict,mutect2"

fix_af:
  container: "docker://hydragenetics/common:0.0.1"

freebayes:
  container: "docker://hydragenetics/freebayes:1.3.1"

bed_split:
  container: "docker://hydragenetics/common:0.0.1"
